---
kind: Namespace
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: myapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hub.hnrx.de:32769/matthias/myapp:$BUILD_NUMBER
        ports:
        - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: myapp-service
  namespace: myapp
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 5000
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.hnrx.de
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp-service
          servicePort: 5000
